--========================================
--CAT_PERMISO
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_PERMISO_ID
    START WITH 12025
    INCREMENT BY 1
    MAXVALUE 9999999999
    MINVALUE 12025
    NOCYCLE
    NOCACHE
    ORDER;

-- TABLA: CAT_PERMISO
CREATE TABLE ADJSS.CAT_PERMISO (
    ID_CAT_PERMISO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(500 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- INDICE PK
CREATE UNIQUE INDEX ADJSS.IDX_CAT_PERMISO_NOMBRE
ON ADJSS.CAT_PERMISO (NOMBRE)
TABLESPACE APP_MOMEMTUM_CAT01_IDX
NOLOGGING;

-- RESTRICCIÓN UNIQUE PARA NOMBRE
ALTER TABLE ADJSS.CAT_PERMISO
ADD CONSTRAINT UQ_CAT_PERMISO_NOMBRE
UNIQUE (NOMBRE)
USING INDEX ADJSS.IDX_CAT_PERMISO_NOMBRE;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_PERMISO IS 'CATALOGO DE PERMISOS';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.ID_CAT_PERMISO IS 'ID NUMERICO DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.NOMBRE IS 'NOMBRE UNICO DEL PERMISO';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.DESCRIPCION IS 'DESCRIPCIÓN BREVE DEL PERMISO';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES.';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREO EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_PERMISO.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ULTIMA MODIFICACIÓN';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_PERMISO_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_PERMISO
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_PERMISO IS NULL THEN
            :NEW.ID_CAT_PERMISO := ADJSS.SEQ_CAT_PERMISO_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;
        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTRO DE PRUEBA
INSERT INTO TECHDEV.CAT_PERMISO (NOMBRE, DESCRIPCION)
VALUES('ELIMINAR_USUARIOS', 'PERMISO PARA ELIMINAR USUARIOS');

--========================================
-- CAT_ROL
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_ROL_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_ROL
CREATE TABLE ADJSS.CAT_ROL (
    ID_CAT_ROL NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(500 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_ROL PRIMARY KEY (ID_CAT_ROL),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_ROL_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_ROL IS 'CATALOGO DE ROLES';
COMMENT ON COLUMN ADJSS.CAT_ROL.ID_CAT_ROL IS 'ID NUMERICO DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_ROL.NOMBRE IS 'NOMBRE UNICO DEL ROL';
COMMENT ON COLUMN ADJSS.CAT_ROL.DESCRIPCION IS 'DESCRIPCIÓN BREVE DE LOS ROLES';
COMMENT ON COLUMN ADJSS.CAT_ROL.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES.';
COMMENT ON COLUMN ADJSS.CAT_ROL.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREO EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_ROL.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_ROL.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ULTIMA MODIFICACIÓN';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_ROL_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_ROL
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_ROL IS NULL THEN
            :NEW.ID_CAT_ROL := ADJSS.SEQ_CAT_ROL_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;
        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTRO DE PRUEBA
INSERT INTO ADJSS.CAT_ROL (NOMBRE, DESCRIPCION)
VALUES('INSTRUCTOR', 'DOCENTE DE LOS CURSOS');

-- PRUEBA PARA VER SI LOS TRIGGERS FUNCIONAN
UPDATE ADJSS.CAT_ROL
SET NOMBRE = 'DOCENTE',
    DESCRIPCION = 'PERSONAL ACADEMICO RESPONSABLE DE IMPARTIR LOS CURSOS'
WHERE ID_CAT_ROL = 1;

--========================================
-- CAT_TIPO_PLAN
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_PLAN_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO_PLAN
CREATE TABLE ADJSS.CAT_TIPO_PLAN (
    ID_CAT_TIPO_PLAN NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(500 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO_PLAN PRIMARY KEY (ID_CAT_TIPO_PLAN),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_PLAN_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO_PLAN IS 'CATALOGO DE PLANES (MEMBRESIAS)';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.ID_CAT_TIPO_PLAN IS 'ID NUMERICO DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.NOMBRE IS 'NOMBRE UNICO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.DESCRIPCION IS 'DESCRIPCIÓN BREVE';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES.';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREO EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PLAN.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ULTIMA MODIFICACIÓN';

-- TRIGGER
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_PLAN_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO_PLAN
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_TIPO_PLAN IS NULL THEN
            :NEW.ID_CAT_TIPO_PLAN := ADJSS.SEQ_CAT_TIPO_PLAN_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;
        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO_PLAN (NOMBRE, DESCRIPCION)
VALUES ('PLUS', 'ACCESO A CURSOS EN VIVO Y GRABADOS');

INSERT INTO ADJSS.CAT_TIPO_PLAN (NOMBRE, DESCRIPCION)
VALUES ('BEGINNER', 'ACCESO A CURSOS GRABADOS');

-- PRUEBA PARA VER SI LOS TRIGGERS FUNCIONAN
UPDATE ADJSS.CAT_TIPO_PLAN
SET NOMBRE = 'PRINCIPIANTE',
    DESCRIPCION = 'PLAN PARA PRINCIPIANTES CON CURSOS GRABADOS'
WHERE ID_CAT_TIPO_PLAN = 2;

--========================================
-- CAT_PLATAFORMA
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_PLATAFORMA_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_PLATAFORMA
CREATE TABLE ADJSS.CAT_PLATAFORMA (
    ID_CAT_PLATAFORMA NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_PLATAFORMA PRIMARY KEY (ID_CAT_PLATAFORMA),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_PLATAFORMA_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_PLATAFORMA IS 'CATÁLOGO DE PLATAFORMAS DISPONIBLES';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.ID_CAT_PLATAFORMA IS 'ID NUMÉRICO DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.NOMBRE IS 'NOMBRE ÚNICO DE LA PLATAFORMA';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.DESCRIPCION IS 'DESCRIPCIÓN BREVE DE LA PLATAFORMA';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_PLATAFORMA.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ÚLTIMA MODIFICACIÓN';

-- TRIGGER
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_PLATAFORMA_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_PLATAFORMA
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_PLATAFORMA IS NULL THEN
            :NEW.ID_CAT_PLATAFORMA := ADJSS.SEQ_CAT_PLATAFORMA_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;
        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_PLATAFORMA (NOMBRE, DESCRIPCION)
VALUES ('MICROSOFT TEAMS', 'PLATAFORMA ACCESIBLE DESDE NAVEGADORES WEB');

INSERT INTO ADJSS.CAT_PLATAFORMA (NOMBRE, DESCRIPCION)
VALUES ('GOOGLE MEET', 'PLATAFORMA ACCESIBLE DESDE APLICACIONES MÓVILES');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_PLATAFORMA
SET NOMBRE = 'ZOOM',
    DESCRIPCION = 'VERSIÓN PARA DISPOSITIVOS MÓVILES DE LA PLATAFORMA'
WHERE ID_CAT_PLATAFORMA = 2;

--========================================
-- CAT_TIPO
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO
CREATE TABLE ADJSS.CAT_TIPO (
    ID_CAT_TIPO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO PRIMARY KEY (ID_CAT_TIPO),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO IS 'CATÁLOGO GENERAL DE TIPOS';
COMMENT ON COLUMN ADJSS.CAT_TIPO.ID_CAT_TIPO IS 'ID NUMÉRICO DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO.NOMBRE IS 'NOMBRE ÚNICO DEL TIPO';
COMMENT ON COLUMN ADJSS.CAT_TIPO.DESCRIPCION IS 'DESCRIPCIÓN BREVE DEL TIPO';
COMMENT ON COLUMN ADJSS.CAT_TIPO.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES';
COMMENT ON COLUMN ADJSS.CAT_TIPO.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ÚLTIMA MODIFICACIÓN';

-- TRIGGER
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    -- Obtener el usuario actual
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);
    
    IF INSERTING THEN
        IF :NEW.ID_CAT_TIPO IS NULL THEN
            :NEW.ID_CAT_TIPO := ADJSS.SEQ_CAT_TIPO_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO (NOMBRE, DESCRIPCION)
VALUES ('TIPO A', 'TIPO GENERAL DE CLASIFICACIÓN A');

INSERT INTO ADJSS.CAT_TIPO (NOMBRE, DESCRIPCION)
VALUES ('TIPO B', 'TIPO GENERAL DE CLASIFICACIÓN B');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_TIPO
SET NOMBRE = 'TIPO BETA',
    DESCRIPCION = 'TIPO BETA, ACTUALIZADO'
WHERE ID_CAT_TIPO = 2;

--========================================
-- CAT_TIPO_PREGUNTA
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_PREGUNTA_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO_PREGUNTA
CREATE TABLE ADJSS.CAT_TIPO_PREGUNTA (
    ID_CAT_TIPO_PREGUNTA NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO_PREGUNTA PRIMARY KEY (ID_CAT_TIPO_PREGUNTA),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_PREGUNTA_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO_PREGUNTA IS 'CATÁLOGO DE TIPOS DE PREGUNTA (ABIERTA, OPCIÓN MÚLTIPLE, ETC.)';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.ID_CAT_TIPO_PREGUNTA IS 'IDENTIFICADOR NUMÉRICO DEL TIPO DE PREGUNTA';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.NOMBRE IS 'NOMBRE ÚNICO DEL TIPO DE PREGUNTA';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.DESCRIPCION IS 'DESCRIPCIÓN BREVE DEL TIPO DE PREGUNTA';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.CREADO_POR IS 'CAPTURA EL USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_PREGUNTA.MODIFICADO_POR IS 'CAPTURA EL USUARIO QUE HIZO LA ÚLTIMA MODIFICACIÓN';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_PREGUNTA_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO_PREGUNTA
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    -- Obtener el usuario actual
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        -- Asignar ID autoincremental si no viene informado
        IF :NEW.ID_CAT_TIPO_PREGUNTA IS NULL THEN
            :NEW.ID_CAT_TIPO_PREGUNTA := ADJSS.SEQ_CAT_TIPO_PREGUNTA_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO_PREGUNTA (NOMBRE, DESCRIPCION)
VALUES ('PREGUNTA ABIERTA', 'RESPUESTA LIBRE POR PARTE DEL USUARIO');

INSERT INTO ADJSS.CAT_TIPO_PREGUNTA (NOMBRE, DESCRIPCION)
VALUES ('OPCIÓN MÚLTIPLE', 'RESPUESTA SELECCIONANDO UNA O MÁS OPCIONES');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_TIPO_PREGUNTA
SET DESCRIPCION = 'PREGUNTA ABIERTA CON CAMPO DE TEXTO'
WHERE ID_CAT_TIPO_PREGUNTA = 1;

--========================================
-- CAT_ESTADO_GLOBAL
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_ESTADO_GLOBAL_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_ESTADO_GLOBAL
CREATE TABLE ADJSS.CAT_ESTADO_GLOBAL (
    ID_CAT_ESTADO_GLOBAL NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(20 CHAR) NOT NULL,
    ENTIDAD VARCHAR2(30 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(100 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_ESTADO_GLOBAL PRIMARY KEY (ID_CAT_ESTADO_GLOBAL),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_ESTADO_GLOBAL_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_ESTADO_GLOBAL IS 'CATÁLOGO DE ESTADOS GLOBALES PARA DIVERSAS ENTIDADES DEL SISTEMA';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.ID_CAT_ESTADO_GLOBAL IS 'IDENTIFICADOR NUMÉRICO DEL ESTADO GLOBAL';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.NOMBRE IS 'NOMBRE ÚNICO DEL ESTADO (EJ. ACTIVO, INACTIVO, etc.)';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.ENTIDAD IS 'ENTIDAD A LA QUE APLICA EL ESTADO (USUARIO, CURSO, etc.)';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.DESCRIPCION IS 'DESCRIPCIÓN DEL ESTADO GLOBAL';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.FE_CREACION IS 'FECHA DE CREACIÓN, NO MODIFICABLE';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.FE_ULTIMA_MODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_ESTADO_GLOBAL.MODIFICADO_POR IS 'USUARIO QUE MODIFICÓ POR ÚLTIMA VEZ EL REGISTRO';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_ESTADO_GLOBAL_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_ESTADO_GLOBAL
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_ESTADO_GLOBAL IS NULL THEN
            :NEW.ID_CAT_ESTADO_GLOBAL := ADJSS.SEQ_CAT_ESTADO_GLOBAL_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_ESTADO_GLOBAL (NOMBRE, ENTIDAD, DESCRIPCION)
VALUES ('ACTIVO', 'USUARIO', 'USUARIO CON ACCESO AL SISTEMA');

INSERT INTO ADJSS.CAT_ESTADO_GLOBAL (NOMBRE, ENTIDAD, DESCRIPCION)
VALUES ('INACTIVO', 'USUARIO', 'USUARIO DESHABILITADO TEMPORALMENTE');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_ESTADO_GLOBAL
SET DESCRIPCION = 'ESTADO QUE INDICA QUE EL USUARIO PUEDE OPERAR NORMALMENTE'
WHERE ID_CAT_ESTADO_GLOBAL = 1;

--========================================
-- CAT_IDIOMA
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_IDIOMA_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_IDIOMA
CREATE TABLE ADJSS.CAT_IDIOMA (
    ID_CAT_IDIOMA NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_IDIOMA PRIMARY KEY (ID_CAT_IDIOMA),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_IDIOMA_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_IDIOMA IS 'CATÁLOGO DE IDIOMAS PARA CURSOS, CONTENIDOS Y USUARIOS';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.ID_CAT_IDIOMA IS 'IDENTIFICADOR NUMÉRICO DEL IDIOMA';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.NOMBRE IS 'NOMBRE DEL IDIOMA (EJ. ESPAÑOL, INGLÉS, FRANCÉS)';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.FE_CREACION IS 'SE ESTABLECE AL INSERTAR, NO SE MODIFICA EN UPDATES';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.FE_ULTIMA_MODIFICACION IS 'SE ACTUALIZA EN CADA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_IDIOMA.MODIFICADO_POR IS 'USUARIO QUE HIZO LA ÚLTIMA MODIFICACIÓN';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_IDIOMA_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_IDIOMA
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_IDIOMA IS NULL THEN
            :NEW.ID_CAT_IDIOMA := ADJSS.SEQ_CAT_IDIOMA_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_IDIOMA (NOMBRE)
VALUES ('ESPAÑOL');

INSERT INTO ADJSS.CAT_IDIOMA (NOMBRE)
VALUES ('INGLÉS');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_IDIOMA
SET NOMBRE = 'ENGLISH'
WHERE ID_CAT_IDIOMA = 2;

--========================================
-- CAT_NIVEL
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_NIVEL_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_NIVEL
CREATE TABLE ADJSS.CAT_NIVEL (
    ID_CAT_NIVEL NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(250 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_NIVEL PRIMARY KEY (ID_CAT_NIVEL),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_NIVEL_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_NIVEL IS 'CATÁLOGO DE NIVELES DE DIFICULTAD O PROGRESIÓN';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.ID_CAT_NIVEL IS 'IDENTIFICADOR ÚNICO DEL NIVEL';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.NOMBRE IS 'NOMBRE DEL NIVEL (EJ. PRINCIPIANTE, INTERMEDIO, AVANZADO)';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.DESCRIPCION IS 'DESCRIPCIÓN OPCIONAL DEL NIVEL';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.FE_CREACION IS 'TIMESTAMP AUTOMÁTICO AL CREAR EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.FE_ULTIMA_MODIFICACION IS 'TIMESTAMP DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_NIVEL.MODIFICADO_POR IS 'USUARIO QUE MODIFICÓ POR ÚLTIMA VEZ';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_NIVEL_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_NIVEL
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_NIVEL IS NULL THEN
            :NEW.ID_CAT_NIVEL := ADJSS.SEQ_CAT_NIVEL_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_NIVEL (NOMBRE, DESCRIPCION)
VALUES ('PRINCIPIANTE', 'NIVEL BÁSICO PARA NUEVOS USUARIOS');

INSERT INTO ADJSS.CAT_NIVEL (NOMBRE, DESCRIPCION)
VALUES ('INTERMEDIO', 'USUARIOS CON CONOCIMIENTOS PREVIOS');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_NIVEL
SET DESCRIPCION = 'USUARIOS QUE COMPRENDEN LOS FUNDAMENTOS Y BUSCAN PROFUNDIZAR'
WHERE ID_CAT_NIVEL = 2;

--========================================
-- CAT_TIPO_CONTENIDO
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_CONTENIDO_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO_CONTENIDO
CREATE TABLE ADJSS.CAT_TIPO_CONTENIDO (
    ID_CAT_TIPO_CONTENIDO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(250 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO_CONTENIDO PRIMARY KEY (ID_CAT_TIPO_CONTENIDO),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_CONTENIDO_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO_CONTENIDO IS 'CATÁLOGO DE TIPOS DE CONTENIDO (VIDEO, DOCUMENTO, INTERACTIVO, ETC.)';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.ID_CAT_TIPO_CONTENIDO IS 'IDENTIFICADOR ÚNICO DEL TIPO DE CONTENIDO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.NOMBRE IS 'NOMBRE ÚNICO DEL TIPO DE CONTENIDO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.DESCRIPCION IS 'DESCRIPCIÓN OPCIONAL DEL TIPO DE CONTENIDO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.FE_CREACION IS 'TIMESTAMP DE CREACIÓN, NO SE MODIFICA';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.FE_ULTIMA_MODIFICACION IS 'TIMESTAMP DE LA ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CONTENIDO.MODIFICADO_POR IS 'USUARIO QUE REALIZÓ LA ÚLTIMA MODIFICACIÓN';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_CONTENIDO_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO_CONTENIDO
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_TIPO_CONTENIDO IS NULL THEN
            :NEW.ID_CAT_TIPO_CONTENIDO := ADJSS.SEQ_CAT_TIPO_CONTENIDO_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO_CONTENIDO (NOMBRE, DESCRIPCION)
VALUES ('VIDEO', 'CONTENIDO MULTIMEDIA EN FORMATO AUDIOVISUAL');

INSERT INTO ADJSS.CAT_TIPO_CONTENIDO (NOMBRE, DESCRIPCION)
VALUES ('DOCUMENTO', 'CONTENIDO EN FORMATO DE TEXTO O PDF');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_TIPO_CONTENIDO
SET DESCRIPCION = 'ARCHIVOS EN FORMATO PDF, WORD U OTROS DOCUMENTALES'
WHERE ID_CAT_TIPO_CONTENIDO = 2;

--========================================
-- CAT_TIPO_RECURSO
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_RECURSO_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO_RECURSO
CREATE TABLE ADJSS.CAT_TIPO_RECURSO (
    ID_CAT_TIPO_RECURSO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(250 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO_RECURSO PRIMARY KEY (ID_CAT_TIPO_RECURSO),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_RECURSO_NOMBRE UNIQUE (NOMBRE)
)
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO_RECURSO IS 'CATÁLOGO DE TIPOS DE RECURSO (IMAGEN, ENLACE, ARCHIVO, ETC.)';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.ID_CAT_TIPO_RECURSO IS 'IDENTIFICADOR ÚNICO DEL TIPO DE RECURSO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.NOMBRE IS 'NOMBRE DEL TIPO DE RECURSO, DEBE SER ÚNICO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.DESCRIPCION IS 'DESCRIPCIÓN OPCIONAL DEL TIPO DE RECURSO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.FE_CREACION IS 'TIMESTAMP DE CREACIÓN, NO SE MODIFICA';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.FE_ULTIMA_MODIFICACION IS 'TIMESTAMP DE LA ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_RECURSO.MODIFICADO_POR IS 'USUARIO QUE MODIFICÓ POR ÚLTIMA VEZ';

-- TRIGGER DE AUDITORÍA
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_RECURSO_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO_RECURSO
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_TIPO_RECURSO IS NULL THEN
            :NEW.ID_CAT_TIPO_RECURSO := ADJSS.SEQ_CAT_TIPO_RECURSO_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO_RECURSO (NOMBRE, DESCRIPCION)
VALUES ('IMAGEN', 'ARCHIVO VISUAL COMO PNG, JPG, SVG');

INSERT INTO ADJSS.CAT_TIPO_RECURSO (NOMBRE, DESCRIPCION)
VALUES ('ENLACE', 'HIPERVÍNCULO A RECURSOS EXTERNOS');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_TIPO_RECURSO
SET DESCRIPCION = 'REFERENCIA A CONTENIDO EXTERNO VINCULADO'
WHERE ID_CAT_TIPO_RECURSO = 2;

--========================================
--CAT_TIPO_CERTIFICACION
--========================================

-- SECUENCIA ID AUTOINCREMENTAL
CREATE SEQUENCE ADJSS.SEQ_CAT_TIPO_CERTIFICACION_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- TABLA: CAT_TIPO_CERTIFICACION
CREATE TABLE ADJSS.CAT_TIPO_CERTIFICACION (
    ID_CAT_TIPO_CERTIFICACION NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    FE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR2(30 CHAR),
    FE_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR VARCHAR2(30 CHAR),
    -- RESTRICCIÓN PK
    CONSTRAINT PK_CAT_TIPO_CERTIFICACION PRIMARY KEY (ID_CAT_TIPO_CERTIFICACION),
    -- RESTRICCIÓN NOMBRE ÚNICO
    CONSTRAINT UQ_CAT_TIPO_CERTIFICACION_NOMBRE UNIQUE (NOMBRE)
)
-- TABLESPACE CATALOGOS
TABLESPACE APP_MOMEMTUM_CAT01_DAT
LOGGING;

-- COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE ADJSS.CAT_TIPO_CERTIFICACION IS 'CATÁLOGO DE TIPOS DE CERTIFICACIÓN (OFICIAL, INTERNA, EXTERNA)';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.ID_CAT_TIPO_CERTIFICACION IS 'IDENTIFICADOR ÚNICO DEL TIPO DE CERTIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.NOMBRE IS 'NOMBRE DEL TIPO DE CERTIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.DESCRIPCION IS 'DESCRIPCIÓN OPCIONAL DEL TIPO DE CERTIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.FE_CREACION IS 'FECHA DE CREACIÓN DEL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.CREADO_POR IS 'USUARIO QUE CREÓ EL REGISTRO';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.FE_ULTIMA_MODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ADJSS.CAT_TIPO_CERTIFICACION.MODIFICADO_POR IS 'USUARIO QUE MODIFICÓ POR ÚLTIMA VEZ';

-- TRIGGER
CREATE OR REPLACE TRIGGER ADJSS.TRG_CAT_TIPO_CERTIFICACION_AUDIT
BEFORE INSERT OR UPDATE ON ADJSS.CAT_TIPO_CERTIFICACION
FOR EACH ROW
DECLARE
    v_usuario VARCHAR2(30);
BEGIN
    v_usuario := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), USER);

    IF INSERTING THEN
        IF :NEW.ID_CAT_TIPO_CERTIFICACION IS NULL THEN
            :NEW.ID_CAT_TIPO_CERTIFICACION := ADJSS.SEQ_CAT_TIPO_CERTIFICACION_ID.NEXTVAL;
        END IF;

        :NEW.FE_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := v_usuario;
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

    ELSIF UPDATING THEN
        :NEW.FE_ULTIMA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := v_usuario;

        :NEW.FE_CREACION := :OLD.FE_CREACION;
        :NEW.CREADO_POR := :OLD.CREADO_POR;
    END IF;
END;
/

-- REGISTROS DE PRUEBA
INSERT INTO ADJSS.CAT_TIPO_CERTIFICACION (NOMBRE, DESCRIPCION)
VALUES ('INTERNA', 'CERTIFICACIÓN OTORGADA POR LA ORGANIZACIÓN');

INSERT INTO ADJSS.CAT_TIPO_CERTIFICACION (NOMBRE, DESCRIPCION)
VALUES ('OFICIAL', 'CERTIFICACIÓN AVALADA POR UNA ENTIDAD EXTERNA');

-- PRUEBA DE ACTUALIZACIÓN
UPDATE ADJSS.CAT_TIPO_CERTIFICACION
SET DESCRIPCION = 'CERTIFICACIÓN FORMAL AVALADA POR UNA INSTITUCIÓN'
WHERE ID_CAT_TIPO_CERTIFICACION = 2;
